[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lokamspace"
version = "0.1.0"
description = "Lokamspace Garage Bot"
requires-python = ">=3.8"

[tool.setuptools]
packages = ["server.src", "agents.GarageBot"] 