"""initial migration

Revision ID: 570be24cba77
Revises: 8a7b3c9d2e1f
Create Date: 2025-06-08 20:42:03.005919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '570be24cba77'
down_revision: Union[str, None] = '8a7b3c9d2e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surveys')
    
    # Add status column as nullable first
    op.add_column('service_records', sa.Column('status', sa.String(length=50), nullable=True))
    
    # Set default value for existing records
    op.execute("UPDATE service_records SET status = 'pending' WHERE status IS NULL")
    
    # Make the column NOT NULL
    op.alter_column('service_records', 'status',
                    existing_type=sa.String(length=50),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_records', 'status')
    op.create_table('surveys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('call_interaction_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('overall_feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('overall_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timeliness_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cleanliness_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('advisor_helpfulness_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('work_quality_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('recommendation_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('action_items', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['call_interaction_id'], ['call_interactions.id'], name=op.f('surveys_call_interaction_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('surveys_pkey')),
    sa.UniqueConstraint('call_interaction_id', name=op.f('surveys_call_interaction_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
