"""add_secret_key_preview_to_api_keys

Revision ID: 36d7468dee11
Revises: 9457dcecfd01
Create Date: 2025-08-01 16:35:53.709046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36d7468dee11'
down_revision: Union[str, None] = '9457dcecfd01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add the column as nullable first
    op.add_column('api_keys', sa.Column('secret_key_preview', sa.String(length=255), nullable=True))
    
    # Step 2: Update existing records with a preview based on their ID
    # Since we can't recover the original keys, we'll use a placeholder that shows it's from existing data
    connection = op.get_bind()
    connection.execute(
        sa.text("UPDATE api_keys SET secret_key_preview = 'sk-' || substr(CAST(id AS TEXT), 1, 4) || '...' || substr(CAST(id AS TEXT), -4) WHERE secret_key_preview IS NULL")
    )
    
    # Step 3: Make the column non-nullable
    op.alter_column('api_keys', 'secret_key_preview', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'secret_key_preview')
    # ### end Alembic commands ### 