"""Added score column in CallMetricScore

Revision ID: 48c52f0bd047
Revises: 1212c00b49f1
Create Date: 2025-06-15 08:26:20.236653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48c52f0bd047'
down_revision: Union[str, None] = '1212c00b49f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_metric_scores', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('call_metric_scores', 'score')
