"""move_is_demo_from_call_to_service_record

Revision ID: 5f4675588be8
Revises: 14fdc9bb275c
Create Date: 2025-07-14 15:43:30.857545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f4675588be8'
down_revision: Union[str, None] = '14fdc9bb275c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_demo column to service_records table
    op.add_column('servicerecords', sa.Column('is_demo', sa.Boolean(), nullable=False, server_default='false'))
    
    # Copy is_demo values from calls to service_records
    op.execute("""
        UPDATE servicerecords
        SET is_demo = calls.is_demo
        FROM calls
        WHERE calls.service_record_id = servicerecords.id
    """)
    
    # Remove is_demo column from calls table
    op.drop_column('calls', 'is_demo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_demo column back to calls table
    op.add_column('calls', sa.Column('is_demo', sa.Boolean(), nullable=False, server_default='false'))
    
    # Copy is_demo values from service_records to calls
    op.execute("""
        UPDATE calls
        SET is_demo = servicerecords.is_demo
        FROM servicerecords
        WHERE calls.service_record_id = servicerecords.id
    """)
    
    # Remove is_demo column from service_records table
    op.drop_column('servicerecords', 'is_demo')
    # ### end Alembic commands ### 