"""remove_phone_fields_add_google_review_link

Revision ID: 8733de17b25a
Revises: 36d7468dee11
Create Date: 2025-08-05 19:03:03.740057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8733de17b25a'
down_revision: Union[str, None] = '36d7468dee11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('google_review_link', sa.String(length=500), nullable=True))
    op.drop_column('organizations', 'phone_booking')
    op.drop_column('organizations', 'phone_feedback')
    op.drop_column('organizations', 'phone_inquiry')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('phone_inquiry', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('phone_feedback', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('phone_booking', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('organizations', 'google_review_link')
    # ### end Alembic commands ### 