"""Update service records, calls and call feedback models

Revision ID: c26403c0bed5
Revises: 981fc91cc022
Create Date: 2025-07-13 12:35:01.312906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c26403c0bed5'
down_revision: Union[str, None] = '981fc91cc022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed incorrect organization table drop
    op.add_column('call_feedback', sa.Column('kpis', sa.JSON(), nullable=True))
    op.add_column('call_feedback', sa.Column('type', sa.String(length=20), nullable=True))
    op.drop_column('call_feedback', 'positives')
    op.drop_column('call_feedback', 'content')
    op.drop_column('call_feedback', 'detractos')
    op.drop_column('call_feedback', 'action_items')
    op.add_column('calls', sa.Column('call_summary', sa.Text(), nullable=True))
    op.drop_column('servicerecords', 'overall_feedback')
    op.drop_column('servicerecords', 'positive_mentions')
    op.drop_column('servicerecords', 'areas_to_improve')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicerecords', sa.Column('areas_to_improve', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('servicerecords', sa.Column('positive_mentions', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('servicerecords', sa.Column('overall_feedback', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('calls', 'call_summary')
    op.add_column('call_feedback', sa.Column('action_items', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('call_feedback', sa.Column('detractos', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('call_feedback', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('call_feedback', sa.Column('positives', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('call_feedback', 'type')
    op.drop_column('call_feedback', 'kpis')
    # Removed incorrect organization table creation
    # ### end Alembic commands ### 