"""Adding missing columns

Revision ID: d5660a252811
Revises: 8733de17b25a
Create Date: 2025-08-07 05:08:52.778968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5660a252811'
down_revision: Union[str, None] = '8733de17b25a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('google_review_link', sa.String(length=500), nullable=True))
    op.drop_column('organizations', 'phone_inquiry')
    op.drop_column('organizations', 'phone_booking')
    op.drop_column('organizations', 'phone_feedback')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('phone_feedback', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('phone_booking', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('phone_inquiry', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('organizations', 'google_review_link')
    # ### end Alembic commands ### 