"""Added new tables and columns for metric calculation

Revision ID: e46e4fbfcdd8
Revises: 7cc8d4e5b778
Create Date: 2025-06-19 20:36:39.787316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e46e4fbfcdd8'
down_revision: Union[str, None] = '7cc8d4e5b778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('detractos', sa.Text(), nullable=False),
    sa.Column('positives', sa.Text(), nullable=False),
    sa.Column('action_items', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('calls', sa.Column('cost', sa.Float(), nullable=True))
    op.add_column('calls', sa.Column('success_metric', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('schedule_start_time', sa.DateTime(), nullable=True))
    op.add_column('organizations', sa.Column('schedule_end_time', sa.DateTime(), nullable=True))
    op.add_column('service_records', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_records', 'summary')
    op.drop_column('organizations', 'schedule_end_time')
    op.drop_column('organizations', 'schedule_start_time')
    op.drop_column('calls', 'success_metric')
    op.drop_column('calls', 'cost')
    op.drop_table('transcripts')
    op.drop_table('call_feedbacks')
    # ### end Alembic commands ###
