"""Add campaign_id to call table

Revision ID: ff35580cd839
Revises: a1585aff9741
Create Date: 2025-07-05 17:44:02.735168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff35580cd839'
down_revision: Union[str, None] = 'a1585aff9741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_file')
    op.add_column('call', sa.Column('campaign_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'call', 'campaign', ['campaign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'call', type_='foreignkey')
    op.drop_column('call', 'campaign_id')
    op.create_table('knowledge_file',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('knowledge_file_organization_id_fkey')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], name=op.f('knowledge_file_uploaded_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_file_pkey'))
    )
    # ### end Alembic commands ### 