"""renamed from pending to READY_TO_DIAL

Revision ID: 7ae2baec751c
Revises: 9aad239a83ba
Create Date: 2025-06-17 20:08:20.794683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae2baec751c'
down_revision: Union[str, None] = '9aad239a83ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Change this to your actual enum type name
enum_type_name = 'servicestatus'  # Usually lowercase of the class name
def upgrade() -> None:
    op.execute("ALTER TYPE {} RENAME VALUE 'PENDING' TO 'READY_TO_DIAL'".format(enum_type_name))
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("ALTER TYPE {} RENAME VALUE 'READY_TO_DIAL' TO 'PENDING'".format(enum_type_name))
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
