"""Added service_manager_number and service_manager_email cloumns in organisation

Revision ID: 7cc8d4e5b778
Revises: 7ae2baec751c
Create Date: 2025-06-18 19:17:19.761321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cc8d4e5b778'
down_revision: Union[str, None] = '7ae2baec751c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('service_manager_email', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('service_manager_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'service_manager_number')
    op.drop_column('organizations', 'service_manager_email')
    # ### end Alembic commands ###
