"""Added organization_id in CallMetricScore table

Revision ID: 9aad239a83ba
Revises: 48c52f0bd047
Create Date: 2025-06-15 12:38:55.739004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aad239a83ba'
down_revision: Union[str, None] = '48c52f0bd047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_metric_scores', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'call_metric_scores', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'call_metric_scores', type_='foreignkey')
    op.drop_column('call_metric_scores', 'organization_id')
    # ### end Alembic commands ###
